In [1]:
import numpy as np

In [2]:
np.random.seed(42)

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def segmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))

# 2 Input "And" Gate

In [4]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])
X, y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 0, 0, 1]))

In [5]:
w1 = np.random.rand()
w2 = np.random.rand()
b = np.random.rand()
f"{w1=}, {w2=}, {b=}"

'w1=0.3745401188473625, w2=0.9507143064099162, b=0.7319939418114051'

In [6]:
def forward(x, w1, w2, b):
    s1 = x[0] * w1
    s2 = x[1] * w2
    a = s1 + s2 + b
    z = sigmoid(a)
    return z, a

In [7]:
forward(X[0], w1, w2, b)

(0.6752426767850529, 0.7319939418114051)

In [8]:
def loss(X, y, w1, w2, b):
    loss = 0
    for x, y_true in zip(X, y):
        y_pred = forward(x, w1, w2, b)[0]
        loss += 0.5 * (y_true - y_pred) ** 2
    return loss

In [9]:
loss(X, y, w1, w2, b)

0.8723062541831995

In [10]:
def backward(X, y, w1, w2, b):
    del_w1 = 0
    del_w2 = 0
    del_b = 0
    for x, y_true in zip(X, y):
        y_pred, a= forward(x, w1, w2, b)
        del_z = y_pred - y_true
        del_a = segmoid_prime(a)
        del_s1 = x[0]
        del_s2 = x[1]
        del_w1 += del_z * del_a * del_s1
        del_w2 += del_z * del_a * del_s2
        del_b += del_z * del_a
    return del_w1, del_w2, del_b

In [11]:
w1, w2, b

(0.3745401188473625, 0.9507143064099162, 0.7319939418114051)

In [12]:
backward(X, y, w1, w2, b)

(0.12895768951083897, 0.10006797336465945, 0.3884862448293551)

In [13]:
lrt = 1
for i in range(1000):
    dw1, dw2, db = backward(X, y, w1, w2, b)
    w1 -= lrt * dw1
    w2 -= lrt * dw2
    b -= lrt * db
    
    if i % 100 == 0:
        print(loss(X, y, w1, w2, b))

0.6908301603053685
0.06295926569256312
0.031105599627844992
0.019991964359721254
0.014535723695468315
0.011342857610109686
0.00926384212131284
0.007809453198562053
0.006738350061413663
0.005918456844047879


In [14]:
forward(X[0], w1, w2, b)[0], forward(X[1], w1, w2, b)[0], forward(X[2], w1, w2, b)[0], forward(X[3], w1, w2, b)[0]

(0.0002453041398875406,
 0.05558170956557133,
 0.05558170896863149,
 0.9338466313512799)

In [15]:
def And2(x1, x2):
    return int(round(forward([x1, x2], w1, w2, b)[0], 0))

In [16]:
And2(0, 0), And2(0, 1), And2(1, 0), And2(1, 1)

(0, 0, 0, 1)

# 2 Input OR Gate

In [17]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 1])
X, y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 1, 1, 1]))

In [18]:
w = np.random.rand(2)
b = np.random.rand(1)
f"{w=}, {b=}"

'w=array([0.59865848, 0.15601864]), b=array([0.15599452])'

In [19]:
def forward(x, w, b):
    s = np.dot(x, w) + b
    z = sigmoid(s)
    return z, s

forward(X, w, b)

(array([0.53891974, 0.57737657, 0.68019172, 0.71313758]),
 array([0.15599452, 0.31201316, 0.754653  , 0.91067164]))

In [24]:
def loss(X, y, w, b):
    loss = 0
    for x, y_true in zip(X, y):
        y_pred = forward(x, w, b)[0]
        loss += 0.5 * (y_true - y_pred) ** 2
    return loss[0]

loss(X, y, w, b)

0.00023772288558921554

In [25]:
def backward(X, y, w, b):
    del_w = np.zeros_like(w)
    del_b = np.zeros_like(b)

    y_pred, s = forward(X, w, b)
    del_z = y_pred - y
    del_s = segmoid_prime(s)
    del_w += np.dot(del_z * del_s, X)
    del_b += np.sum(del_z * del_s, axis=0, keepdims=True)
    return del_w, del_b


backward(X, y, w, b)

(array([-0.00010416, -0.00010416]), array([5.23330382e-05]))

In [32]:
lrt = 1
for i in range(10000):
    dw, db = backward(X, y, w, b)
    w -= lrt * dw
    b -= lrt * db
    
    if i % 1000 == 0:
        print(loss(X, y, w, b))

3.8336772544823964e-05
3.770136011768429e-05
3.708661300386518e-05
3.649154048406891e-05
3.591521412148862e-05
3.535676294588601e-05
3.481536907753192e-05
3.4290263744889717e-05
3.3780723655308554e-05
3.328606768276056e-05


In [33]:
def Or2(x1, x2):
    return forward([x1, x2], w, b)[0].round().astype(int)[0]

In [34]:
Or2(0, 0), Or2(0, 1), Or2(1, 0), Or2(1, 1)

(0, 1, 1, 1)

# 2 Input XOR Gate

In [35]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])
X, y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 1, 1, 0]))

2 Inputs <br>
1 hidden layer with 2 neurons <br>
1 output <br>


In [36]:
w1 = np.random.rand(2, 2)
w2 = np.random.rand(2, 1)
b1 = np.random.rand(2)
b2 = np.random.rand(1)
print(f"{w1=}\n{w2=}\n{b1=}, {b2=}")

w1=array([[0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])
w2=array([[0.02058449],
       [0.96990985]])
b1=array([0.83244264, 0.21233911]), b2=array([0.18182497])


In [37]:
def forward(x, w1, w2, b1, b2):
    s1 = np.dot(x, w1) + b1
    z1 = sigmoid(s1)
    s2 = np.dot(z1, w2) + b2
    z2 = sigmoid(s2)
    return z2, s2, z1, s1

forward(X[0], w1, w2, b1, b2)

(array([0.67533599]),
 array([0.7324195]),
 array([0.69687117, 0.55288622]),
 array([0.83244264, 0.21233911]))

In [38]:
def loss(X, y, w1, w2, b1, b2):
    y_pred, _, _, _ = forward(X, w1, w2, b1, b2)
    loss = 0
    for y_true, y_pred in zip(y, y_pred):
        loss += 0.5 * (y_true - y_pred) ** 2
    return loss[0]


loss(X, y, w1, w2, b1, b2)

0.5823104395794695

In [39]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([5, 6])
a, b, a@b, a*b,

(array([[1, 2],
        [3, 4]]),
 array([5, 6]),
 array([17, 39]),
 array([[ 5, 12],
        [15, 24]]))

In [40]:
np.tensordot(a, b, axes = 0), np.tensordot(a, b, axes = 0).shape

(array([[[ 5,  6],
         [10, 12]],
 
        [[15, 18],
         [20, 24]]]),
 (2, 2, 2))

In [41]:
def backward(X, y, w1, w2, b1, b2):
    del_w1 = np.zeros_like(w1)
    del_w2 = np.zeros_like(w2)
    del_b1 = np.zeros_like(b1)
    del_b2 = np.zeros_like(b2)

    y_pred, s2, z1, s1 = forward(X, w1, w2, b1, b2)

    del_z2 = y_pred.reshape(y.shape) - y

    del_s2 = segmoid_prime(s2).reshape(y.shape)

    del_w2 += np.dot(z1.T, del_z2 * del_s2).reshape(w2.shape)

    del_z1 = np.tensordot(del_z2 * del_s2, w2.T, axes=0).reshape(z1.shape)
    del_s1 = segmoid_prime(s1)
    del_w1 += np.dot(X.T, del_z1 * del_s1)

    del_b2 += np.sum(del_z2 * del_s2, axis=0)
    del_b1 += np.sum(del_z1 * del_s1, axis=0)
    return del_w1, del_w2, del_b1, del_b2


backward(X, y, w1, w2, b1, b2)

(array([[0.00019447, 0.00636977],
        [0.00024919, 0.0051897 ]]),
 array([[0.13027526],
        [0.11807031]]),
 array([0.00064652, 0.0300295 ]),
 array([0.17297179]))

In [43]:
lrt = 1
for i in range(10000):
    dw1, dw2, db1, db2 = backward(X, y, w1, w2, b1, b2)
    w1 -= lrt * dw1
    w2 -= lrt * dw2
    b1 -= lrt * db1
    b2 -= lrt * db2
    
    if i % 1000 == 0:
        print(loss(X, y, w1, w2, b1, b2))

0.25036274763139776
0.2503269697085619
0.25029752786920706
0.25027288500359646
0.25025196245409054
0.2502339813030435
0.2502183652300175
0.2502046787949729
0.2501925869547734
0.2501818277614838


In [44]:
def XOR2(x1, x2):
    return forward([x1, x2], w1, w2, b1, b2)[0].round().astype(int)[0]

In [45]:
XOR2(0, 0), XOR2(0, 1), XOR2(1, 0), XOR2(1, 1)

(0, 0, 1, 1)

# Half Adder

In [46]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0, 0], [0, 1], [0, 1], [1, 0]])
X, y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[0, 0],
        [0, 1],
        [0, 1],
        [1, 0]]))

y: [carry, sum]

In [47]:
w1 = np.random.rand(2, 2)
w2 = np.random.rand(2, 2)
b1 = np.random.rand(2)
b2 = np.random.rand(2)
print(f"{w1=}\n{w2=}\n{b1=}, {b2=}")

w1=array([[0.18340451, 0.30424224],
       [0.52475643, 0.43194502]])
w2=array([[0.29122914, 0.61185289],
       [0.13949386, 0.29214465]])
b1=array([0.36636184, 0.45606998]), b2=array([0.78517596, 0.19967378])


In [48]:
def forward(x, w1, w2, b1, b2):
    s1 = np.dot(x, w1) + b1
    z1 = sigmoid(s1)
    s2 = np.dot(z1, w2) + b2
    z2 = sigmoid(s2)
    return z2, s2, z1, s1

forward(X[0], w1, w2, b1, b2)

(array([0.73934203, 0.67696041]),
 array([1.04255155, 0.73983793]),
 array([0.59057958, 0.61208145]),
 array([0.36636184, 0.45606998]))

In [49]:
def loss(X, y, w1, w2, b1, b2):
    y_pred, _, _, _ = forward(X, w1, w2, b1, b2)
    loss = 0
    for y_true, y_pred in zip(y, y_pred):
        loss += 0.5 * (y_true - y_pred) ** 2
    return loss[0]

loss(X, y, w1, w2, b1, b2)

0.8606660555854708

In [50]:
def backward(X, y, w1, w2, b1, b2):
    del_w1 = np.zeros_like(w1)
    del_w2 = np.zeros_like(w2)
    del_b1 = np.zeros_like(b1)
    del_b2 = np.zeros_like(b2)

    y_pred, s2, z1, s1 = forward(X, w1, w2, b1, b2)

    del_z2 = y_pred - y

    del_s2 = segmoid_prime(s2)

    del_w2 += np.dot(z1.T, del_z2 * del_s2)

    del_z1 = np.dot(del_z2 * del_s2, w2.T)

    del_s1 = segmoid_prime(s1)

    del_w1 += np.dot(X.T, del_z1 * del_s1)

    del_b2 += np.sum(del_z2 * del_s2, axis=0)

    del_b1 += np.sum(del_z1 * del_s1, axis=0)

    return del_w1, del_w2, del_b1, del_b2

backward(X, y, w1, w2, b1, b2)

(array([[0.01448021, 0.00651866],
        [0.01490373, 0.00672137]]),
 array([[0.23948212, 0.10896086],
        [0.24816377, 0.11217719]]),
 array([0.04686942, 0.02173682]),
 array([0.37890735, 0.16378072]))

In [51]:
lrt = 1
for i in range(10000):
    dw1, dw2, db1, db2 = backward(X, y, w1, w2, b1, b2)
    w1 -= lrt * dw1
    w2 -= lrt * dw2
    b1 -= lrt * db1
    b2 -= lrt * db2
    
    if i % 1000 == 0:
        print(loss(X, y, w1, w2, b1, b2))


0.6077822607383208
0.0013778283884493636
0.0006310441106331835
0.0004102703607594124
0.0003038967924311705
0.000241253876267653
0.0001999707951521975
0.00017071689617119263
0.00014890584897134522
0.00013201977926380662


In [52]:
def half_adder(x1, x2):
    s = np.array([x1, x2])
    z, _, _, _ = forward(s, w1, w2, b1, b2)
    return z.round().astype(int)

In [53]:
half_adder(0, 0), half_adder(0, 1), half_adder(1, 0), half_adder(1, 1)

(array([0, 0]), array([0, 1]), array([0, 1]), array([1, 0]))